/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesAuthenticatedRouteImport } from './routes/workspaces/_authenticated'
import { Route as WorkspacesAuthenticatedIndexRouteImport } from './routes/workspaces/_authenticated/index'
import { Route as WorkspacesAuthenticatedWorkspaceIdRouteImport } from './routes/workspaces/_authenticated/$workspaceId'
import { Route as WorkspacesAuthenticatedWorkspaceIdIndexRouteImport } from './routes/workspaces/_authenticated/$workspaceId/index'
import { Route as WorkspacesAuthenticatedWorkspaceIdTasksIndexRouteImport } from './routes/workspaces/_authenticated/$workspaceId/tasks/index'
import { Route as WorkspacesAuthenticatedWorkspaceIdBoardsIndexRouteImport } from './routes/workspaces/_authenticated/$workspaceId/boards/index'
import { Route as WorkspacesAuthenticatedWorkspaceIdAgentsIndexRouteImport } from './routes/workspaces/_authenticated/$workspaceId/agents/index'
import { Route as WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRouteImport } from './routes/workspaces/_authenticated/$workspaceId/tasks/$taskId'
import { Route as WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRouteImport } from './routes/workspaces/_authenticated/$workspaceId/boards/$boardId/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesAuthenticatedRoute = WorkspacesAuthenticatedRouteImport.update({
  id: '/workspaces/_authenticated',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesAuthenticatedIndexRoute =
  WorkspacesAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesAuthenticatedRoute,
  } as any)
const WorkspacesAuthenticatedWorkspaceIdRoute =
  WorkspacesAuthenticatedWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => WorkspacesAuthenticatedRoute,
  } as any)
const WorkspacesAuthenticatedWorkspaceIdIndexRoute =
  WorkspacesAuthenticatedWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesAuthenticatedWorkspaceIdRoute,
  } as any)
const WorkspacesAuthenticatedWorkspaceIdTasksIndexRoute =
  WorkspacesAuthenticatedWorkspaceIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => WorkspacesAuthenticatedWorkspaceIdRoute,
  } as any)
const WorkspacesAuthenticatedWorkspaceIdBoardsIndexRoute =
  WorkspacesAuthenticatedWorkspaceIdBoardsIndexRouteImport.update({
    id: '/boards/',
    path: '/boards/',
    getParentRoute: () => WorkspacesAuthenticatedWorkspaceIdRoute,
  } as any)
const WorkspacesAuthenticatedWorkspaceIdAgentsIndexRoute =
  WorkspacesAuthenticatedWorkspaceIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => WorkspacesAuthenticatedWorkspaceIdRoute,
  } as any)
const WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRoute =
  WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => WorkspacesAuthenticatedWorkspaceIdRoute,
  } as any)
const WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRoute =
  WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRouteImport.update({
    id: '/boards/$boardId/',
    path: '/boards/$boardId/',
    getParentRoute: () => WorkspacesAuthenticatedWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/workspaces': typeof WorkspacesAuthenticatedRouteWithChildren
  '/workspaces/$workspaceId': typeof WorkspacesAuthenticatedWorkspaceIdRouteWithChildren
  '/workspaces/': typeof WorkspacesAuthenticatedIndexRoute
  '/workspaces/$workspaceId/': typeof WorkspacesAuthenticatedWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/tasks/$taskId': typeof WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRoute
  '/workspaces/$workspaceId/agents/': typeof WorkspacesAuthenticatedWorkspaceIdAgentsIndexRoute
  '/workspaces/$workspaceId/boards/': typeof WorkspacesAuthenticatedWorkspaceIdBoardsIndexRoute
  '/workspaces/$workspaceId/tasks/': typeof WorkspacesAuthenticatedWorkspaceIdTasksIndexRoute
  '/workspaces/$workspaceId/boards/$boardId/': typeof WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/workspaces': typeof WorkspacesAuthenticatedIndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesAuthenticatedWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/tasks/$taskId': typeof WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRoute
  '/workspaces/$workspaceId/agents': typeof WorkspacesAuthenticatedWorkspaceIdAgentsIndexRoute
  '/workspaces/$workspaceId/boards': typeof WorkspacesAuthenticatedWorkspaceIdBoardsIndexRoute
  '/workspaces/$workspaceId/tasks': typeof WorkspacesAuthenticatedWorkspaceIdTasksIndexRoute
  '/workspaces/$workspaceId/boards/$boardId': typeof WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/workspaces/_authenticated': typeof WorkspacesAuthenticatedRouteWithChildren
  '/workspaces/_authenticated/$workspaceId': typeof WorkspacesAuthenticatedWorkspaceIdRouteWithChildren
  '/workspaces/_authenticated/': typeof WorkspacesAuthenticatedIndexRoute
  '/workspaces/_authenticated/$workspaceId/': typeof WorkspacesAuthenticatedWorkspaceIdIndexRoute
  '/workspaces/_authenticated/$workspaceId/tasks/$taskId': typeof WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRoute
  '/workspaces/_authenticated/$workspaceId/agents/': typeof WorkspacesAuthenticatedWorkspaceIdAgentsIndexRoute
  '/workspaces/_authenticated/$workspaceId/boards/': typeof WorkspacesAuthenticatedWorkspaceIdBoardsIndexRoute
  '/workspaces/_authenticated/$workspaceId/tasks/': typeof WorkspacesAuthenticatedWorkspaceIdTasksIndexRoute
  '/workspaces/_authenticated/$workspaceId/boards/$boardId/': typeof WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/tasks/$taskId'
    | '/workspaces/$workspaceId/agents/'
    | '/workspaces/$workspaceId/boards/'
    | '/workspaces/$workspaceId/tasks/'
    | '/workspaces/$workspaceId/boards/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/tasks/$taskId'
    | '/workspaces/$workspaceId/agents'
    | '/workspaces/$workspaceId/boards'
    | '/workspaces/$workspaceId/tasks'
    | '/workspaces/$workspaceId/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/workspaces/_authenticated'
    | '/workspaces/_authenticated/$workspaceId'
    | '/workspaces/_authenticated/'
    | '/workspaces/_authenticated/$workspaceId/'
    | '/workspaces/_authenticated/$workspaceId/tasks/$taskId'
    | '/workspaces/_authenticated/$workspaceId/agents/'
    | '/workspaces/_authenticated/$workspaceId/boards/'
    | '/workspaces/_authenticated/$workspaceId/tasks/'
    | '/workspaces/_authenticated/$workspaceId/boards/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  WorkspacesAuthenticatedRoute: typeof WorkspacesAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/_authenticated': {
      id: '/workspaces/_authenticated'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/_authenticated/': {
      id: '/workspaces/_authenticated/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesAuthenticatedIndexRouteImport
      parentRoute: typeof WorkspacesAuthenticatedRoute
    }
    '/workspaces/_authenticated/$workspaceId': {
      id: '/workspaces/_authenticated/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesAuthenticatedWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesAuthenticatedRoute
    }
    '/workspaces/_authenticated/$workspaceId/': {
      id: '/workspaces/_authenticated/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesAuthenticatedWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesAuthenticatedWorkspaceIdRoute
    }
    '/workspaces/_authenticated/$workspaceId/tasks/': {
      id: '/workspaces/_authenticated/$workspaceId/tasks/'
      path: '/tasks'
      fullPath: '/workspaces/$workspaceId/tasks/'
      preLoaderRoute: typeof WorkspacesAuthenticatedWorkspaceIdTasksIndexRouteImport
      parentRoute: typeof WorkspacesAuthenticatedWorkspaceIdRoute
    }
    '/workspaces/_authenticated/$workspaceId/boards/': {
      id: '/workspaces/_authenticated/$workspaceId/boards/'
      path: '/boards'
      fullPath: '/workspaces/$workspaceId/boards/'
      preLoaderRoute: typeof WorkspacesAuthenticatedWorkspaceIdBoardsIndexRouteImport
      parentRoute: typeof WorkspacesAuthenticatedWorkspaceIdRoute
    }
    '/workspaces/_authenticated/$workspaceId/agents/': {
      id: '/workspaces/_authenticated/$workspaceId/agents/'
      path: '/agents'
      fullPath: '/workspaces/$workspaceId/agents/'
      preLoaderRoute: typeof WorkspacesAuthenticatedWorkspaceIdAgentsIndexRouteImport
      parentRoute: typeof WorkspacesAuthenticatedWorkspaceIdRoute
    }
    '/workspaces/_authenticated/$workspaceId/tasks/$taskId': {
      id: '/workspaces/_authenticated/$workspaceId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/workspaces/$workspaceId/tasks/$taskId'
      preLoaderRoute: typeof WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRouteImport
      parentRoute: typeof WorkspacesAuthenticatedWorkspaceIdRoute
    }
    '/workspaces/_authenticated/$workspaceId/boards/$boardId/': {
      id: '/workspaces/_authenticated/$workspaceId/boards/$boardId/'
      path: '/boards/$boardId'
      fullPath: '/workspaces/$workspaceId/boards/$boardId/'
      preLoaderRoute: typeof WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRouteImport
      parentRoute: typeof WorkspacesAuthenticatedWorkspaceIdRoute
    }
  }
}

interface WorkspacesAuthenticatedWorkspaceIdRouteChildren {
  WorkspacesAuthenticatedWorkspaceIdIndexRoute: typeof WorkspacesAuthenticatedWorkspaceIdIndexRoute
  WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRoute: typeof WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRoute
  WorkspacesAuthenticatedWorkspaceIdAgentsIndexRoute: typeof WorkspacesAuthenticatedWorkspaceIdAgentsIndexRoute
  WorkspacesAuthenticatedWorkspaceIdBoardsIndexRoute: typeof WorkspacesAuthenticatedWorkspaceIdBoardsIndexRoute
  WorkspacesAuthenticatedWorkspaceIdTasksIndexRoute: typeof WorkspacesAuthenticatedWorkspaceIdTasksIndexRoute
  WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRoute: typeof WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRoute
}

const WorkspacesAuthenticatedWorkspaceIdRouteChildren: WorkspacesAuthenticatedWorkspaceIdRouteChildren =
  {
    WorkspacesAuthenticatedWorkspaceIdIndexRoute:
      WorkspacesAuthenticatedWorkspaceIdIndexRoute,
    WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRoute:
      WorkspacesAuthenticatedWorkspaceIdTasksTaskIdRoute,
    WorkspacesAuthenticatedWorkspaceIdAgentsIndexRoute:
      WorkspacesAuthenticatedWorkspaceIdAgentsIndexRoute,
    WorkspacesAuthenticatedWorkspaceIdBoardsIndexRoute:
      WorkspacesAuthenticatedWorkspaceIdBoardsIndexRoute,
    WorkspacesAuthenticatedWorkspaceIdTasksIndexRoute:
      WorkspacesAuthenticatedWorkspaceIdTasksIndexRoute,
    WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRoute:
      WorkspacesAuthenticatedWorkspaceIdBoardsBoardIdIndexRoute,
  }

const WorkspacesAuthenticatedWorkspaceIdRouteWithChildren =
  WorkspacesAuthenticatedWorkspaceIdRoute._addFileChildren(
    WorkspacesAuthenticatedWorkspaceIdRouteChildren,
  )

interface WorkspacesAuthenticatedRouteChildren {
  WorkspacesAuthenticatedWorkspaceIdRoute: typeof WorkspacesAuthenticatedWorkspaceIdRouteWithChildren
  WorkspacesAuthenticatedIndexRoute: typeof WorkspacesAuthenticatedIndexRoute
}

const WorkspacesAuthenticatedRouteChildren: WorkspacesAuthenticatedRouteChildren =
  {
    WorkspacesAuthenticatedWorkspaceIdRoute:
      WorkspacesAuthenticatedWorkspaceIdRouteWithChildren,
    WorkspacesAuthenticatedIndexRoute: WorkspacesAuthenticatedIndexRoute,
  }

const WorkspacesAuthenticatedRouteWithChildren =
  WorkspacesAuthenticatedRoute._addFileChildren(
    WorkspacesAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  WorkspacesAuthenticatedRoute: WorkspacesAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
